(function(){function q(){function q(){if(!document.querySelector("a.skip-link")){var a=document.createElement("a");a.className="skip-link";a.href="#maincontent";a.textContent="Skip to main content";document.body.insertBefore(a,document.body.firstChild);a.addEventListener("click",function(){setTimeout(function(){var a=document.getElementById("maincontent");a&&(a.setAttribute("tabindex","-1"),a.focus({preventScroll:!1}))},0)})}}function r(){q();var a=document.getElementById("maincontent");a||((a=document.querySelector("main")||
document.querySelector("main, #content, .td-main-content-wrap, .td-outer-wrap, #td-outer-wrap, .tdc-content-wrap, .td-container, .td-content-wrap, .site-content, #primary")||document.body)&&"main"!==a.tagName.toLowerCase()&&a.setAttribute("role","main"),a&&(a.id="maincontent",a.hasAttribute("tabindex")||a.setAttribute("tabindex","-1")))}function u(a){function b(a){return a.querySelector(":scope > a, :scope > button")}function e(a){return a.querySelector(":scope > .sub-menu")}function f(a,b){a&&(b?
(a.style.setProperty("display","block","important"),a.style.setProperty("opacity","1","important"),a.style.setProperty("visibility","visible","important"),a.style.pointerEvents="auto"):(a.style.removeProperty("display"),a.style.removeProperty("opacity"),a.style.removeProperty("visibility"),a.style.removeProperty("pointer-events")),b?(a.setAttribute("aria-hidden","false"),m&&(a.inert=!1)):(m&&(a.inert=!0),a.setAttribute("aria-hidden","true")))}function c(a){return a.classList.contains("is-open")||
a.classList.contains("tdb-hover")}function g(d,c){c=!1!==(c||{}).moveFocus;var k=b(d),h=e(d);k&&h&&(l.forEach(function(b){b!==d&&a.contains(b)&&p(b,{returnFocus:!1})}),d.classList.add("is-open","tdb-hover"),k.setAttribute("aria-expanded","true"),h.id||(h.id="mm-"+Math.random().toString(36).slice(2)),k.setAttribute("aria-controls",h.id),h.setAttribute("role","group"),f(h,!0),c&&(c=h.querySelector('a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'))&&
c.focus())}function p(a,c){c=!1!==(c||{}).returnFocus;var d=b(a),h=e(a);d&&h&&(c&&h.contains(document.activeElement)&&d.focus(),a.classList.remove("is-open","tdb-hover"),d.setAttribute("aria-expanded","false"),f(h,!1))}if(a&&!a.hasAttribute("data-a11y-menu")){a.setAttribute("data-a11y-menu","1");a.querySelectorAll(".tdb-sub-menu-icon").forEach(function(a){a.setAttribute("aria-hidden","true")});var n=Array.prototype.slice.call(a.querySelectorAll(":scope > li")),l=n.filter(function(a){return a.classList.contains("tdb-mega-menu")||
a.classList.contains("menu-item-has-children")});l.forEach(function(a){var d=b(a),k=e(a);d&&k&&(d.setAttribute("aria-haspopup","true"),d.setAttribute("aria-expanded","false"),k.id||(k.id="mm-"+Math.random().toString(36).slice(2)),d.setAttribute("aria-controls",k.id),f(k,!1),a.addEventListener("mouseenter",function(){g(a,{moveFocus:!1})}),a.addEventListener("mouseleave",function(){p(a,{returnFocus:!1})}),d.addEventListener("keydown",function(d){if("Enter"===d.key||" "===d.key)d.preventDefault(),c(a)?
p(a):g(a);else if("ArrowDown"===d.key)d.preventDefault(),c(a)||g(a),d=a.querySelectorAll(':scope > .sub-menu a[href], :scope > .sub-menu button:not([disabled]), :scope > .sub-menu [tabindex]:not([tabindex="-1"])'),d.length&&d[0].focus();else if("ArrowUp"===d.key)d.preventDefault(),c(a)||g(a,{moveFocus:!1}),d=a.querySelectorAll(':scope > .sub-menu a[href], :scope > .sub-menu button:not([disabled]), :scope > .sub-menu [tabindex]:not([tabindex="-1"])'),d.length&&d[d.length-1].focus();else if("ArrowRight"===
d.key||"ArrowLeft"===d.key){d.preventDefault();var e=n.indexOf(a);-1<e&&(d=b(n["ArrowRight"===d.key?(e+1)%n.length:(e-1+n.length)%n.length]))&&d.focus()}}),k.addEventListener("keydown",function(d){"Escape"===d.key&&(d.preventDefault(),p(a))}),a.addEventListener("focusout",function(){setTimeout(function(){a.contains(document.activeElement)||p(a,{returnFocus:!1})},0)}))});Array.prototype.slice.call(a.querySelectorAll("li.menu-item-has-children")).filter(function(a){return-1===n.indexOf(a)}).forEach(function(a){var d=
a.querySelector(":scope > a, :scope > button"),b=a.querySelector(":scope > .sub-menu");b&&d&&(d.hasAttribute("aria-haspopup")||d.setAttribute("aria-haspopup","true"),d.hasAttribute("aria-expanded")||d.setAttribute("aria-expanded","false"),b.id||(b.id="mm-"+Math.random().toString(36).slice(2)),d.setAttribute("aria-controls",b.id),b.setAttribute("aria-hidden","true"),a.addEventListener("mouseenter",function(){a.classList.add("is-open","tdb-hover");b.style.setProperty("display","block","important");
b.style.setProperty("opacity","1","important");b.style.setProperty("visibility","visible","important");b.style.pointerEvents="auto";b.setAttribute("aria-hidden","false");m&&(b.inert=!1);d.setAttribute("aria-expanded","true")}),a.addEventListener("mouseleave",function(){b.contains(document.activeElement)||(a.classList.remove("is-open","tdb-hover"),b.style.removeProperty("display"),b.style.removeProperty("opacity"),b.style.removeProperty("visibility"),b.style.removeProperty("pointer-events"),b.setAttribute("aria-hidden",
"true"),m&&(b.inert=!0),d.setAttribute("aria-expanded","false"))}))});a.addEventListener("focusin",function(b){if(b=b.target.closest(".sub-menu")){for(b=b.closest("li");b&&b.parentElement!==a;)b=b.parentElement&&b.parentElement.closest?b.parentElement.closest("li"):null;b&&(-1===l.indexOf(b)||c(b)||g(b,{moveFocus:!1}))}});a.addEventListener("keydown",function(a){var b=a.target.closest(".td-next-prev-wrap a");!b||"Enter"!==a.key&&" "!==a.key||(a.preventDefault(),b.click())})}}if(document.body&&document.body.classList.contains("a11y-enabled")&&
!document.documentElement.hasAttribute("data-a11y-initialized")){document.documentElement.setAttribute("data-a11y-initialized","true");var m="inert"in HTMLElement.prototype;"loading"===document.readyState?document.addEventListener("DOMContentLoaded",r,{once:!0}):r();setTimeout(r,500);(new MutationObserver(r)).observe(document.body,{childList:!0,subtree:!0});document.querySelectorAll(".tdb-block-menu").forEach(u);(new MutationObserver(function(a){a.forEach(function(a){a.addedNodes&&a.addedNodes.forEach(function(a){a instanceof
HTMLElement&&(a.matches&&a.matches(".tdb-block-menu")&&u(a),a.querySelectorAll&&a.querySelectorAll(".tdb-block-menu").forEach(u))})})})).observe(document.body,{childList:!0,subtree:!0});document.addEventListener("keydown",function(a){function b(a){(a=a&&a.querySelector('a[href], button:not([disabled]), [tabindex]:not([tabindex="-1"])'))&&a.focus()}if(-1!=="ArrowDown ArrowUp Home End ArrowLeft ArrowRight".split(" ").indexOf(a.key)){var e=a.target,f=e.closest&&e.closest(".tdb-block-menu");if(f){var c=
e.closest("ul.sub-menu");if(c&&f.contains(c)&&(e=e.closest("li"))&&(f=Array.prototype.slice.call(c.children).filter(function(a){return a.matches("li")}).filter(function(a){return a.querySelector('a[href], button:not([disabled]), [tabindex]:not([tabindex="-1"])')}),f.length)){var g=f.indexOf(e);if(-1!==g)if(a.stopPropagation(),"ArrowRight"===a.key){if(c=e.querySelector(":scope > ul.sub-menu")){a.preventDefault();e.classList.add("is-open","tdb-hover");if(a=e.querySelector(":scope > a, :scope > button"))a.setAttribute("aria-expanded",
"true"),c.id||(c.id="mm-"+Math.random().toString(36).slice(2)),a.setAttribute("aria-controls",c.id);c.style.setProperty("display","block","important");c.style.setProperty("opacity","1","important");c.style.setProperty("visibility","visible","important");c.style.pointerEvents="auto";c.setAttribute("aria-hidden","false");m&&(c.inert=!1);(a=c.querySelector("li"))&&b(a)}}else if("ArrowLeft"===a.key){if(e=c.parentElement&&c.parentElement.closest("li"))if(a.preventDefault(),e.classList.remove("is-open",
"tdb-hover"),c.style.removeProperty("display"),c.style.removeProperty("opacity"),c.style.removeProperty("visibility"),c.style.removeProperty("pointer-events"),c.setAttribute("aria-hidden","true"),m&&(c.inert=!0),a=e.querySelector(":scope > a, :scope > button"))a.setAttribute("aria-expanded","false"),a.focus()}else{c=g;switch(a.key){case "ArrowDown":a.preventDefault();c=(g+1)%f.length;break;case "ArrowUp":a.preventDefault();c=(g-1+f.length)%f.length;break;case "Home":a.preventDefault();c=0;break;case "End":a.preventDefault(),
c=f.length-1}c!==g&&(a=f[c])&&b(a)}}}}},!0);var l=document.querySelectorAll(".td-icon-search, .td-header-search-button, .td-search-btn"),t=document.querySelectorAll(".td-search-wrap, .td-search-box, .td-drop-down-search");if(l.length&&t.length){var v=function(a,b){a.classList.remove("is-open");a.setAttribute("aria-hidden","true");a._untrap&&a._untrap();a._untrap=null;w(a,!1);var e=b||a._trigger;e&&"function"===typeof e.focus&&setTimeout(function(){e.focus()},0)},x=function(a,b){a.classList.add("is-open");
a.setAttribute("aria-hidden","false");w(a,!0);var e=a.querySelector('input[type="search"], input[type="text"]')||a.querySelector('a[href], button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])');e&&e.focus();a._untrap&&a._untrap();a._untrap=z(a,function(){v(a,b)});a._trigger=b||a._trigger},y=function(){return Array.prototype.slice.call(t).find(function(a){return a.classList.contains("is-open")||"false"===a.getAttribute("aria-hidden")})||t[0]},w=function(a,b){Array.prototype.slice.call(document.body.children).forEach(function(e){e!==
a&&(b?(m&&(e.inert=!0),e.setAttribute("aria-hidden","true")):(m&&(e.inert=!1),e.removeAttribute("aria-hidden")))})},z=function(a,b){function e(e){if("Escape"===e.key)e.preventDefault(),b&&b();else if("Tab"===e.key){var c=Array.prototype.slice.call(a.querySelectorAll('a[href], area[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])')).filter(function(a){return null!==a.offsetParent||a===document.activeElement});if(c.length){var f=
c[0];c=c[c.length-1];e.shiftKey&&document.activeElement===f?(e.preventDefault(),c.focus()):e.shiftKey||document.activeElement!==c||(e.preventDefault(),f.focus())}}}a.addEventListener("keydown",e);return function(){a.removeEventListener("keydown",e)}};t.forEach(function(a,b){a.setAttribute("role","dialog");a.setAttribute("aria-modal","true");a.setAttribute("aria-hidden",a.classList.contains("is-open")?"false":"true");a.id||(a.id="search-dialog-"+(b+1));a.hasAttribute("aria-labelledby")||a.hasAttribute("aria-label")||
((b=a.querySelector("h1, h2, h3, [data-dialog-title]"))&&!b.id&&(b.id=a.id+"-title"),b?a.setAttribute("aria-labelledby",b.id):a.setAttribute("aria-label","Search"))});l.forEach(function(a){a.setAttribute("aria-haspopup","dialog");a.setAttribute("aria-expanded","false");a.addEventListener("click",function(b){b.preventDefault();b=y();a.setAttribute("aria-expanded","true");x(b,a)});a.addEventListener("keydown",function(b){if("Enter"===b.key||" "===b.key)b.preventDefault(),a.click()})});document.addEventListener("click",
function(a){if(a=a.target.closest(".td-search-close, .td-icon-close, .td-icon-search-close, .js-search-close"))if(a=a.closest(".td-search-wrap, .td-search-box, .td-drop-down-search")){var b=a._trigger||Array.prototype.slice.call(l).find(function(a){return null!==a.offsetParent});v(a,b);b&&b.setAttribute("aria-expanded","false")}});document.addEventListener("keydown",function(a){if("Escape"===a.key){var b=y();b&&(b.classList.contains("is-open")||"false"===b.getAttribute("aria-hidden"))&&(a.preventDefault(),
a=b._trigger||Array.prototype.slice.call(l).find(function(a){return"true"===a.getAttribute("aria-expanded")}),v(b,a),a&&a.setAttribute("aria-expanded","false"))}});document.addEventListener("focusin",function(a){if((a=a.target.closest(".td-search-wrap, .td-search-box, .td-drop-down-search"))&&("true"===a.getAttribute("aria-hidden")||!a.classList.contains("is-open"))){var b=a._trigger||Array.prototype.slice.call(l)[0];x(a,b);b&&b.setAttribute("aria-expanded","true")}})}}}"loading"===document.readyState?
document.addEventListener("DOMContentLoaded",q,{once:!0}):q()})();
